"""The trace field reference must not drift from the canonical schema.

``labs/TRACE-FIELD-REFERENCE.md`` is generated by
``scripts/export_trace_reference.py`` from the same ``trace_json_schema()``
output that produces ``schemas/trace/trace_event.v1.schema.json``. These tests
pin that the committed page is exactly what the schema would generate, that it
covers every field and event type, and that every documented field has a curated
meaning (so a new schema field cannot slip in undocumented).
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import yaml

from agentsec.trace.schema import TRACE_EVENT_TYPES, trace_json_schema

ROOT = Path(__file__).resolve().parents[2]
REFERENCE = ROOT / "labs" / "TRACE-FIELD-REFERENCE.md"
GENERATOR = ROOT / "scripts" / "export_trace_reference.py"
MKDOCS = ROOT / "mkdocs.yml"


def _load_generator():
    """Import ``scripts/export_trace_reference.py``, which is not a package module."""
    spec = importlib.util.spec_from_file_location("export_trace_reference", GENERATOR)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


generator = _load_generator()


def _schema_fields() -> set[str]:
    schema = trace_json_schema()
    fields: set[str] = set()
    for name, body in schema["$defs"].items():
        fields.update(body.get("properties", {}))
    return fields


def test_reference_matches_fresh_generation():
    assert REFERENCE.is_file(), "labs/TRACE-FIELD-REFERENCE.md is missing"
    checked_in = REFERENCE.read_text(encoding="utf-8")
    assert checked_in == generator.render(), (
        "labs/TRACE-FIELD-REFERENCE.md is out of date; "
        "run `py scripts/export_trace_reference.py`"
    )


def test_reference_documents_every_schema_field_and_event():
    page = REFERENCE.read_text(encoding="utf-8")
    missing_fields = sorted(
        field for field in _schema_fields() if f"`{field}`" not in page
    )
    assert missing_fields == [], f"undocumented schema fields: {missing_fields}"
    missing_events = sorted(
        event for event in TRACE_EVENT_TYPES if f"`{event}`" not in page
    )
    assert missing_events == [], f"undocumented event types: {missing_events}"


def test_every_schema_field_has_a_documented_meaning():
    meanings = generator.FIELD_MEANINGS
    missing = sorted(field for field in _schema_fields() if field not in meanings)
    assert missing == [], (
        "these schema fields have no curated meaning in "
        f"scripts/export_trace_reference.py: {missing}"
    )


def test_reference_is_listed_in_the_mkdocs_navigation():
    config = yaml.safe_load(MKDOCS.read_text(encoding="utf-8"))
    paths: set[str] = set()

    def collect(node):
        if isinstance(node, dict):
            for value in node.values():
                collect(value)
        elif isinstance(node, list):
            for value in node:
                collect(value)
        elif isinstance(node, str):
            paths.add(node)

    collect(config.get("nav"))
    assert "TRACE-FIELD-REFERENCE.md" in paths, (
        "the trace field reference is not in the MkDocs navigation"
    )
