"""Trace package: event schema, redaction, validation, recording and JSONL I/O."""

from .recorder import TraceMeta, TraceRecorder
from .redact import DEFAULT_REDACTOR, Redactor, hash_value, redact_value
from .schema import (
    TRACE_EVENT_TYPES,
    TRACE_SCHEMA_VERSION,
    AgentInputEvent,
    AgentOutputEvent,
    ModelRequestEvent,
    ModelResponseEvent,
    PolicyDecisionEvent,
    RunCompletedEvent,
    RunFailedEvent,
    RunStartedEvent,
    SecurityEvent,
    ToolExecutedEvent,
    ToolRequestedEvent,
    ToolResultEvent,
    TraceEvent,
    TraceEventEnvelope,
    UsageCounts,
    trace_json_schema,
)
from .validate import (
    ValidationIssue,
    ValidationReport,
    load_schema,
    schema_path,
    schema_resource,
    schema_text,
    validate_event,
    validate_jsonl,
)
from .writer import read_events, serialize_event, write_event, write_events

__all__ = [
    "TRACE_EVENT_TYPES",
    "TRACE_SCHEMA_VERSION",
    "AgentInputEvent",
    "AgentOutputEvent",
    "ModelRequestEvent",
    "ModelResponseEvent",
    "PolicyDecisionEvent",
    "RunCompletedEvent",
    "RunFailedEvent",
    "RunStartedEvent",
    "SecurityEvent",
    "ToolExecutedEvent",
    "ToolRequestedEvent",
    "ToolResultEvent",
    "TraceEvent",
    "TraceEventEnvelope",
    "UsageCounts",
    "trace_json_schema",
    "TraceMeta",
    "TraceRecorder",
    "DEFAULT_REDACTOR",
    "Redactor",
    "hash_value",
    "redact_value",
    "ValidationIssue",
    "ValidationReport",
    "load_schema",
    "schema_path",
    "schema_resource",
    "schema_text",
    "validate_event",
    "validate_jsonl",
    "read_events",
    "serialize_event",
    "write_event",
    "write_events",
]
